module.exports = {
    INVALID_USER_DATA: 'Invalid user data.',
    INVALID_USERNAME_LENGTH: 'Username must be at least 5 symbols long.',
    INVALID_PASSWORD_LENGTH: 'Password must be at least 5 symbols long.',
    INVALID_FIRSTNAME_LENGTH: 'Firstname must be at least 2 symbols long.',
    INVALID_LASTNAME_LENGTH: 'Lastname must be at least 2 symbols long.',
    INVALID_PASSWORD_RESEMBLANCE: 'There is discrepancy between password and confirm password.',
    INVALID_EMAIL_ADDRESS: 'Email address must be in format example@example.example',
    INVALID_RECIPE_TITLE: 'Title must be at least 3 symbols long',
    INVALID_RECIPE_DESCRIPTION: 'Description must be at least 3 symbols long',
    INVALID_RECIPE_CATEGORY: 'Category must be at least 3 symbols long',
    INVALID_RECIPE_IMAGEURL: 'Image url must be at least 10 symbols long',
    INVALID_RECIPE_COOKINGTIME: 'Cooking time must be at least 1 minute',
    INVALID_RECIPE_SERVINGS: 'Servings must be at least for 1 person',
    INVALID_TOKEN: 'Invalid token',
    EMPTY_RECIPES: 'There aren`t any recipes',
    EMPTY_INGREDIENTS_COLLECTION: 'Ingredients cannot be empty',
    DUPLICATE_USERNAME_OR_EMAIL: 'Username or email already exist in the database.',
    DUPLICATE_KEY_DB: 'duplicate key',
    PRIVATE_KEY: 'some-secret-word!@#$%'
};