{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true,
        "jquery": true
    },
    "parserOptions": {
        "ecmaVersion": 2017,
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "rules": {
        "semi": "warn",
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-unreachable": "warn",
        "no-unused-vars": 0,
        "constructor-super": "warn",
        "valid-typeof": "warn",
        "no-console": 0,
        "curly": "warn",
        "guard-for-in": "warn",
        "no-else-return": "warn",
        "indent": ["warn", 4],
    }
}
